use crate::row_renderer::RowRenderer;
use leptos::*;

/// The default table row renderer. Uses the `<tr>` element. Please note that this
/// is **NOT** a `#[component]`.
#[allow(unused_variables)]
pub fn DefaultTableRowRenderer<Row, Key>(
    // The class attribute for the row element. Generated by the classes provider.
    class: Signal<String>,
    // The row to render.
    row: Row,
    // The index of the row. Starts at 0 for the first body row.
    index: usize,
    // The selected state of the row. True, when the row is selected.
    selected: RwSignal<bool>,
) -> impl IntoView
where
    Row: RowRenderer<Key> + 'static,
    Key: Clone + 'static,
{
    let key = row.key();

    view! {
        <tr
            class=class
            on:click=move |mouse_event| selected.set(true)
        >
            {row.render_row()}
        </tr>
    }
}
