#![deny(missing_docs)]
//! Column index  showcase example.

use ::chrono::NaiveDate;
use derive_more::{Deref, DerefMut};
use leptos::prelude::*;
use leptos::web_sys;
use leptos_struct_table::*;
use std::sync::Arc;

/// Custom row renderer that adds a link to the end of the row
#[allow(unused_variables, non_snake_case)]
pub fn CustomTableRowRenderer(
    // The class attribute for the row element. Generated by the classes provider.
    class: Signal<String>,
    // The row to render.
    row: RwSignal<Book>,
    // The index of the row. Starts at 0 for the first body row.
    index: usize,
    // The selected state of the row. True, when the row is selected.
    selected: Signal<bool>,
    // Event handler callback when this row is selected
    on_select: EventHandler<web_sys::MouseEvent>,
    // Columns to show and their order.
    columns: RwSignal<Vec<BookColumn>>,
) -> impl IntoView {
    view! {
        <tr class=class on:click=move |mouse_event| on_select.run(mouse_event)>
            {TableRow::render_row(row, index, columns)}
            <td>
                <a href=move || format!("/some-path/{}", row.read().title)>"Some link"</a>
            </td>
        </tr>
    }
}

#[component]
#[allow(unused_variables)]
pub fn ColorCellRenderer(
    /// Base cell rendere classes
    #[prop(into)]
    class: String,
    /// Value of this cell
    value: Signal<String>,
    /// Row containing this cell
    row: RwSignal<Book>,
    /// Column Index of the cell. (variant of a generated enum in this example)
    index: BookColumn,
) -> impl IntoView {
    match index {
        BookColumn::Title => view! { <span style="color: blue;">{ value }</span> },
        BookColumn::Author => view! { <span style="color: red;">{ value }</span> },
        BookColumn::PublishDate => view! { <span style="color: green;">{ value }</span> },
        BookColumn::Description => view! { <span style="color: yellow;">{ value }</span> },
    }
}

/// This generates the component BookTable
#[derive(TableRow, Clone)]
#[table(sortable, impl_vec_data_provider, column_index_type = "enum")]
pub struct Book {
    /// Title of the book.
    pub title: String,
    /// Author of the book.
    #[table(renderer = "ColorCellRenderer")]
    pub author: String,
    /// Date when book has been published.
    pub publish_date: Option<NaiveDate>,
    /// Description of the book. Optional.
    #[table(none_value = "-")]
    pub description: Option<String>,
}

/// New-type pattern because otherwise the impl TableRow doesn't work because of orphan rules.
#[derive(Deref, DerefMut, Clone)]
pub struct ArcBook(Arc<Book>);

fn main() {
    _ = console_log::init_with_level(log::Level::Debug);
    console_error_panic_hook::set_once();

    mount_to_body(|| {
        let rows = vec![
            Book {
                title: "The Great Gatsby".to_string(),
                author: "F. Scott Fitzgerald".to_string(),
                publish_date: Some(NaiveDate::from_ymd_opt(1925, 4, 10).unwrap()),
                description: Some(
                    "A story of wealth, love, and the American Dream in the 1920s.".to_string(),
                ),
            },
            Book {
                title: "The Grapes of Wrath".to_string(),
                author: "John Steinbeck".to_string(),
                publish_date: Some(NaiveDate::from_ymd_opt(1939, 4, 14).unwrap()),
                description: None,
            },
            Book {
                title: "Nineteen Eighty-Four".to_string(),
                author: "George Orwell".to_string(),
                publish_date: Some(NaiveDate::from_ymd_opt(1949, 6, 8).unwrap()),
                description: None,
            },
            Book {
                title: "Ulysses".to_string(),
                author: "James Joyce".to_string(),
                publish_date: Some(NaiveDate::from_ymd_opt(1922, 2, 2).unwrap()),
                description: None,
            },
        ];

        view! {
            <table>
                <TableContent rows scroll_container="html" />
            </table>
        }
    })
}
